name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: checkout src
        uses: actions/checkout@v4

      - name: setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.10.0"
          rebar3-version: "3"

      - name: build pages
        run: gleam run -m build

  deploy:
    needs: build

    # redundant but keep regardless
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: deploy pages
        id: deploy
        uses: actions/deploy-pages@v4
