name: build & deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    needs: setup

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: build pages
        run: gleam run -m build

      - name: setup pages
        id: pages
        uses: actions/configure-pages@v5
        with:
          path: ./pages

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
