name: Build and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout src
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: build angular
        run: npm install && npm run build:prod

      - name: publish site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/browser
          branch: live
          token: ${{ GITHUB_TOKEN }}
