name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
